server:
  port: 8080
spring:
  application:
    name: micorservice-consumer-movie
eureka:
  client:
    serviceUrl:
      defaultZone: http://user:123@localhost:8761/eureka
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}
    #${spring.application.name}:${spring.application.instance_id:${server.port}}