server:
  port: 8080
spring:
  application:
    name: micorservice-consumer-movie-ribbon
eureka:
  client:
    serviceUrl:
      defaultZone: http://user:123@localhost:8761/eureka
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}
    #${spring.application.name}:${spring.application.instance_id:${server.port}}
# 配置不使用eureka
ribbon:
  eureka:
   enabled: false
micorservice-provider-user: # 为该服务自定义规则，不会影响其他服务
  ribbon:
    listOfServers: localhost:7901
    