server:
  port: 7901
spring:
  jpa:
    generate-ddl: false
    show-sql: true
    hibernate:
      ddl-auto: none
  datasource:
    platform: h2
    schema: classpath:schema.sql
    data: classpath:data.sql
  application:
    name: micorservice-provider-user
logging:
  level:
    root: INFO
    org.hibernate: INFO
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.hibernate.type.descriptor.sql.BasicExtractor: TRACE
    com.example: DEBUG
eureka:
  client:
    serviceUrl:
      defaultZone: http://user:123@localhost:8761/eureka #http://server1:8671/eureka/ #表示注册到那个注册中心
  instance:
    prefer-ip-address: true #配置在eureka的管控台上的展示
    instance-id: ${spring.application.name}:${spring.application.instance_id:${server.port}} 
 
    #${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}
    