security:
  basic:
    enabled: true
  user:
    name: user
    password: 123
server:  
  port: 8761
eureka:  
  client:  
    register-with-eureka: false  
    fetch-registry: false  #通过eureka.client.registerWithEureka：false和fetchRegistry：false来表明自己是一个eureka server,默认是client
    service-url:  
      defaultZone: http://user:123@localhost:8761/eureka